server:
  port: 3339

security:
  key: fgkdDDleG302Fdl210194kfl34fVdlça1E3

aws:
  endpoint: http://localhost:4566
  region: us-east-1
  access-key: local
  secret-key: local
  dynamodb:
    prefix: dev_

logging:
  level:
    br:
      com:
        teknologi: DEBUG